services:
  - type: web
    name: truepriv-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    plan: free
    region: oregon
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_NAME
        value: "TruePriv Platform"
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: SANCTUM_STATEFUL_DOMAINS
        value: "truepriv-saas.vercel.app,localhost:3000"
      - key: DUAL_RESIDENCY_ENABLED
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: "ep-mute-band-aurnzzzy.c-10.us-east-1.aws.neon.tech;options='endpoint=ep-mute-band-aurnzzzy'"
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: "neondb"
      - key: DB_USERNAME
        value: "neondb_owner"
      - key: DB_PASSWORD
        value: "npg_bacTn3QYZ6hi"
      - key: DB_SSLMODE
        value: "require"
